### PR TITLE
Reload Tinderbox page every 15 minutes automatically

### PR DESCRIPTION
**Pull request by bzfbd**
Reload Tinderbox page every 15 minutes automatically
to not keep showing entirely stale pages.

### CODE REVIEW

**Comment by bzfbd** [comment]
This addresses https://github.com/FreeBSDFoundation/jenkins-tinderbox/pull/3#issuecomment-1236203295

**Comment by bzfbd** [comment]
PING6?  @lwhsu @emaste ?

**Comment by emaste** [comment]
looks fine to me but I'll leave it to @lwhsu since he'll be the one to install the updated file on the server

**Comment by lwhsu** [comment]
Sorry for forgetting this. BTW we're in the middle of updating this page and will include other PRs as well.

**Pull request merged**
